name: Format

on:
  pull_request:
    paths:
      - 'src/**'
      - '.clang-format'

concurrency:
  group: format-${{ github.ref }}
  cancel-in-progress: true

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: DoozyX/clang-format-lint-action@v0.20
        with:
          source: src
          extensions: cpp,h
          clangFormatVersion: 19
